# Generated by Django 5.0.1 on 2024-01-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plants',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_id', models.IntegerField()),
                ('a_id', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('long', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('datePlanted', models.CharField(max_length=60)),
                ('lastChecked', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('about', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='projectManager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('long', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
            ],
        ),
    ]
