# Generated by Django 5.0.1 on 2024-02-03 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plants',
            old_name='id',
            new_name='plantId',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='id',
            new_name='projectId',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='a_id',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='p_id',
        ),
        migrations.AddField(
            model_name='plants',
            name='projectId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.projects'),
        ),
        migrations.AddField(
            model_name='plants',
            name='projectManagerId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.projectmanager'),
        ),
        migrations.AddField(
            model_name='projects',
            name='projectManagerId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.projectmanager'),
        ),
        migrations.AddField(
            model_name='projects',
            name='region',
            field=models.CharField(default='bbs', max_length=30),
        ),
        migrations.AddField(
            model_name='projects',
            name='state',
            field=models.CharField(default='od', max_length=30),
        ),
        migrations.AlterField(
            model_name='plants',
            name='about',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='areas',
            fields=[
                ('areaId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('long', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('projectId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.projects')),
                ('projectManagerId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.projectmanager')),
            ],
        ),
        migrations.AddField(
            model_name='plants',
            name='areaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.areas'),
        ),
    ]
